#!/usr/bin/env python

import subprocess
import optparse

parser = optparse.OptionParser()

parser.add_option("-i", "--interface", dest="interface", help="Interface to change its MAC address.")

parser.parse_args()

interface = input("interface >") 
new_mac = input("new Mac >") 

## Use input with Python3
## Use raw_input with Python2 

print("Initializing MAC Address change to" + interface + " to " + new_mac)

subprocess.call(["ifconfig", interface, "down"])
subprocess.call(["ifconfig", interface, "ether" + new_mac])
subprocess.call(["ifconfig", interface, "up"])
