#!/usr/bin/env python

import subprocess
import optparse

## optparse is a Python library for parsing command-line options. 
parser = optparse.OptionParser()

parser.add_option("-i", "--interface", dest="interface", help="Interface to change its MAC address.")
parser.add_option("-m", "--mac", dest="new_mac", help="New MAC address.")

(options,arguments) = parser.parse_args()

interface = options.interface
new_mac = options.new_mac

## Use input with Python3
## Use raw_input with Python2 

print("Initializing MAC Address change to" + interface + " to " + new_mac)

subprocess.call(["ifconfig", interface, "down"])
subprocess.call(["ifconfig", interface, "ether" + new_mac])
subprocess.call(["ifconfig", interface, "up"])
